### ISSUE TITLE
Set default action to 'sync'

### ISSUE THREAD

**Issue by pythonhacker** [tkhyn/dirsync#2]
anand@toshiba-laptop:~$ dirsync --verbose Documents/tickets/ /tmp/tickets
Traceback (most recent call last):
  File "/usr/local/bin/dirsync", line 9, in <module>
    load_entry_point('dirsync==2.0c1', 'console_scripts', 'dirsync')()
  File "/usr/local/lib/python2.7/dist-packages/dirsync-2.0c1-py2.7.egg/dirsync/syncer.py", line 590, in execute_from_command_line
    sync(options.pop('sourcedir'), options.pop('targetdir'), **options)
  File "/usr/local/lib/python2.7/dist-packages/dirsync-2.0c1-py2.7.egg/dirsync/syncer.py", line 535, in sync
    copier = Syncer(src_dir, tgt_dir, action=action, **options)
  File "/usr/local/lib/python2.7/dist-packages/dirsync-2.0c1-py2.7.egg/dirsync/syncer.py", line 67, in __init__
    self._mainfunc = getattr(self, options['action'])
TypeError: getattr(): attribute name must be string

The default action option needn't be set everytime and can default to 'sync'.

**Comment by pythonhacker** [comment]
I have modified code to create .dirsync folder upon first time run.

**Comment by tkhyn** [comment]
Hi and thanks for reporting,

Commit [c76ff643f27b (bb)](https://bitbucket.org/tkhyn/dirsync/commits/c76ff643f27b) should fix the problem (patch syncer.py or download the [full package](https://bitbucket.org/tkhyn/dirsync/get/bugfix.zip)). Please reopen if it does not, before I release a new version.
