### ISSUE TITLE
Cannot install dirsync in python 3.9.5

### ISSUE THREAD

**Issue by aLuViAn87** [tkhyn/dirsync#41]
Tried installing dirsync with pip and it threw the following exception:

`C:\Project>pip install dirsync
Collecting dirsync
  Using cached dirsync-2.2.5.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\aluvian\pycharmprojects\filecopier\venv\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Aluvian\\AppData\\Local\\Temp\\pip-install-rpxrxsx0\\dirsync_a9467259433
34427bce64710d1a6654d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Aluvian\\AppData\\Local\\Temp\\pip-install-rpxrxsx0\\dirsync_a946725943334427bce64710d1a6654d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.
path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Alu
vian\AppData\Local\Temp\pip-pip-egg-info-oqvk2pgo'
         cwd: C:\Users\Aluvian\AppData\Local\Temp\pip-install-rpxrxsx0\dirsync_a946725943334427bce64710d1a6654d\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\aluvian\pycharmprojects\filecopier\venv\lib\site-packages\setuptools\__init__.py", line 16, in <module>
        import setuptools.version
      File "c:\users\aluvian\pycharmprojects\filecopier\venv\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "c:\users\aluvian\pycharmprojects\filecopier\venv\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
        from pkg_resources.extern import appdirs
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 565, in module_from_spec
      File "c:\users\aluvian\pycharmprojects\filecopier\venv\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
        return self.load_module(spec.name)
      File "c:\users\aluvian\pycharmprojects\filecopier\venv\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
        __import__(extant)
      File "c:\users\aluvian\pycharmprojects\filecopier\venv\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
        import win32com.shell
    ValueError: source code string cannot contain null bytes
`

Pip tries to install different versions of dirsync and the above error is returned for each version. I just copied one version.
There is no issue with Python 3.7.9 (the other version that I had)

**Python version : 3.9.5**
**Windows version : 10 20h2**
**Pip version : 21.1.3**

**Comment by tkhyn** [comment]
I imagine this has been solved by now. dirsync sucessfully installs with with recent python versions.
Please reopen if it is still an issue.
